services:
  vault:
    image: hashicorp/vault:latest
    container_name: jobpost_vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://localhost:8200
      - VAULT_API_ADDR=http://localhost:8200
      - VAULT_DEV_ROOT_TOKEN_ID=admin
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - vault_config:/vault/config
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: jobpost_postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=JobPosting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.17.27
    container_name: jobpost_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: jobpost_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"   # AMQP protokolü
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  vault-init:
    image: hashicorp/vault:latest
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://jobpost_vault:8200
      - VAULT_TOKEN=admin
    command: >
      /bin/sh -c '
        sleep 10;
        vault secrets enable -path=secret kv-v2 || true;
        vault kv put secret/JobPost \
          ConnectionStrings:DefaultConnection="Host=localhost;Port=5432;Database=JobPortal;Username=postgres;Password=123456;" \
          EmployerSettings:DefaultLimitOfJobPosts="2" \
          Elasticsearch:Url="http://localhost:9200" \
          RabbitMQ:ConnectionString="amqp://admin:123456@localhost:5672"
      '

volumes:
  vault_data:
  vault_config:
  postgres_data:
  elasticsearch_data:
  rabbitmq_data:

networks:
  default:
    name: job-portal-network 