services:
  vault:
    image: hashicorp/vault:latest
    container_name: jobportal_vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=admin
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - vault_config:/vault/config
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: jobportal_postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=JobPosting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.17.27
    container_name: jobportal_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://jobportal_elasticsearch:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: jobportal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"   # AMQP protokolü
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  vault-init:
    image: hashicorp/vault:latest
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://jobportal_vault:8200
      - VAULT_TOKEN=admin
    command: >
      /bin/sh -c '
        sleep 2;
        vault secrets enable -path=secret kv-v2 || true;
        vault kv put secret/JobPost \
          ConnectionStrings:DefaultConnection="Host=jobportal_postgres-db;Port=5432;Database=JobPortal;Username=postgres;Password=123456;" \
          EmployerSettings:DefaultLimitOfJobPosts="2" \
          Elasticsearch:Url="http://jobportal_elasticsearch:9200" \
          RabbitMQ:ConnectionString="amqp://admin:123456@jobportal_rabbitmq:5672" \
          Redis:ConnectionString="jobportal_redis:6379"
      '

  redis:
    image: redis:latest
    container_name: jobportal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      sh -c '
        redis-server --daemonize yes &&
        sleep 1 &&
        redis-cli SADD HateWords madara nanay parlak pinpon saksı gıcık gaga enayi düdük çakmak babaçko armut akmak arakçı &&
        redis-server --daemonize no
      '
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  employer-service:
    image: ${DOCKER_REGISTRY-}employerservice
    container_name: jobportal_employer-service
    build:
      context: .
      dockerfile: APIs/EmployerService/JobPortal.EmployerService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - VAULT_ADDR=http://jobportal_vault:8200
      - VAULT_TOKEN=admin
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5010:80"
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  jobposting-service:
    image: ${DOCKER_REGISTRY-}jobpostingservice
    container_name: jobportal_jobposting-service
    build:
      context: .
      dockerfile: APIs/JobPostingService/JobPortal.JobPostingService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - VAULT_ADDR=http://jobportal_vault:8200
      - VAULT_TOKEN=admin
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5020:80"
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: jobportal_api-gateway
    build:
      context: .
      dockerfile: APIs/ApiGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - VAULT_ADDR=http://jobportal_vault:8200
      - VAULT_TOKEN=admin
      - APIGATEWAY_HOST=localhost
      - APIGATEWAY_PORT=5000
      - EMPLOYER_SERVICE_HOST=jobportal_employer-service
      - EMPLOYER_SERVICE_PORT=80
      - JOB_POSTING_SERVICE_HOST=jobportal_jobposting-service
      - JOB_POSTING_SERVICE_PORT=80
    depends_on:
      employer-service:
        condition: service_healthy
      jobposting-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://jobportal_api-gateway:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  vault_data:
  vault_config:
  postgres_data:
  elasticsearch_data:
  rabbitmq_data:
  redis_data: